### ISSUE TITLE
Does oxhttp have IPv6 support?

### ISSUE THREAD

**Issue by nikolaswise** [oxigraph/oxhttp#8]
I've been trying to set a reverse proxy in front of oxigraph with nginx on a private IPv6 network. One of the possibilities to explain my constant 502 results is that oxhttp is refusing connections over IPv6. 

Does this seem likely?

**Comment by Tpt** [comment]
@nikolaswise Hi! Yes, it seems like when `oxigraph` is asked to listen to `localhost`, it seems to only listen to either IPv4 or IPv6 but not both (it's the behavior of [Rust standard library `TcpListener::bind`](https://doc.rust-lang.org/std/net/struct.TcpListener.html#method.bind)). At least, I should make it clear by printing the proper bound value in the CLI output.

To make sure the server is listening to IPv6, you can use the `--bind` option. For example: `--bind '[::1]:2727'`

**Comment by Tpt** [comment]
In the just released version 0.3.14 Oxigraph now properly listen to both IPv4 and IPv6 when asked to listen to `localhost`. I hope it fixes the problem
