### ISSUE TITLE
Add client and server features

### ISSUE THREAD

**Issue by nickfla1** [oxigraph/oxhttp#9]
## Description

It would be nice to have `client` and `server` features to allow compiling only what the user wants. 
As those scopes are already separated I think it shoudl be fairly easy to make this change - also, to prevent breaking changes, the default feature could include both `client` and `server`.

~~I will probably provide  a PR if you think this could be useful.~~ #10

**Comment by Tpt** [comment]
Done in the 0.2.0-alpha.1 release.
